# -*- coding: utf-8 -*-
"""
Created on Sun Sep 21 23:24:31 2025

@author: manju
"""

import streamlit as st
import pandas as pd
import os

st.set_page_config(
    page_title="Daily Stock Scanner",
    page_icon="📈",
    layout="wide"
)

st.title("📊 Daily Stock Scanner Results")

# File path (CSV generated by app.py and committed by GitHub Actions)
csv_file = "top_10_stocks.csv"

if os.path.exists(csv_file):
    df = pd.read_csv(csv_file)

    st.success("✅ Latest Stock Picks Loaded")

    # Show table
    st.dataframe(df, use_container_width=True)

    # Download button
    csv_data = df.to_csv(index=False).encode("utf-8")
    st.download_button(
        label="📥 Download CSV",
        data=csv_data,
        file_name="top_10_stocks.csv",
        mime="text/csv"
    )

else:
    st.warning("⚠️ No results found yet. Please wait for the next scheduled run.")

